export const ADMIN_REGISTER_REQUEST="ADMIN_REGISTER_REQUEST"
export const ADMIN_REGISTER_SUCCESS="ADMIN_REGISTER_SUCCESS"
export const ADMIN_REGISTER_FAIL="ADMIN_REGISTER_FAIL"

export const ADMIN_LOGOUT_SUCCESS="ADMIN_LOGOUT_SUCCESS"

export const ADMIN_LOGIN_REQUEST="ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL="ADMIN_LOGIN_FAIL"


export const GET_ADMINS_REQUEST="GET_ADMINS_REQUEST"
export const GET_ADMINS_SUCCESS="GET_ADMINS_SUCCESS"
export const GET_ADMINS_FAIL="GET_ADMINS_FAIL"


export const GET_ADMIN_REQUEST="GET_ADMIN_REQUEST"
export const GET_ADMIN_SUCCESS="GET_ADMIN_SUCCESS"
export const GET_ADMIN_FAIL="GET_ADMIN_FAIL"


export const DELETE_ADMIN_REQUEST="DELETE_ADMIN_REQUEST"
export const DELETE_ADMIN_SUCCESS="DELETE_ADMIN_SUCCESS"
export const DELETE_ADMIN_FAIL="DELETE_ADMIN_FAIL"


export const UPDATE_ADMIN_REQUEST="UPDATE_ADMIN_REQUEST"
export const UPDATE_ADMIN_SUCCESS="UPDATE_ADMIN_SUCCESS"
export const UPDATE_ADMIN_FAIL="UPDATE_ADMIN_FAIL"