export const CASHIER_REGISTER_REQUEST="CASHIER_REGISTER_REQUEST"
export const CASHIER_REGISTER_SUCCESS="CASHIER_REGISTER_SUCCESS"
export const CASHIER_REGISTER_FAIL="CASHIER_REGISTER_FAIL"

export const CASHIER_LOGOUT_SUCCESS="CASHIER_LOGOUT_SUCCESS"

export const CASHIER_LOGIN_REQUEST="CASHIER_LOGIN_REQUEST"
export const CASHIER_LOGIN_SUCCESS="CASHIER_LOGIN_SUCCESS"
export const CASHIER_LOGIN_FAIL="CASHIER_LOGIN_FAIL"

export const CASHIER_UPDATE_REQUEST="CASHIER_UPDATE_REQUEST"
export const CASHIER_UPDATE_SUCCESS="CASHIER_UPDATE_SUCCESS"
export const CASHIER_UPDATE_FAIL="CASHIER_UPDATE_FAIL"

export const CASHIER_DELETE_REQUEST="CASHIER_DELETE_REQUEST"
export const CASHIER_DELETE_SUCCESS="CASHIER_DELETE_SUCCESS"
export const CASHIER_DELETE_FAIL="CASHIER_DELETE_FAIL"

export const CASHIER_UPDATE_PASSWORD_REQUEST="CASHIER_UPDATE_PASSWORD_REQUEST"
export const CASHIER_UPDATE_PASSWORD_SUCCESS="CASHIER_UPDATE_PASSWORD_SUCCESS"
export const CASHIER_UPDATE_PASSWORD_FAIL="CASHIER_UPDATE_PASSWORD_FAIL"

export const GET_CASHIERS_REQUEST="GET_CASHIERS_REQUEST"
export const GET_CASHIERS_SUCCESS="GET_CASHIERS_SUCCESS"
export const GET_CASHIERS_FAIL="GET_CASHIERS_FAIL"


export const GET_CASHIER_REQUEST="GET_CASHIER_REQUEST"
export const GET_CASHIER_SUCCESS="GET_CASHIER_SUCCESS"
export const GET_CASHIER_FAIL="GET_CASHIER_FAIL"