export const MANAGER_REGISTER_REQUEST="MANAGER_REGISTER_REQUEST"
export const MANAGER_REGISTER_SUCCESS="MANAGER_REGISTER_SUCCESS"
export const MANAGER_REGISTER_FAIL="MANAGER_REGISTER_FAIL"

export const MANAGER_LOGOUT_SUCCESS="MANAGER_LOGOUT_SUCCESS"

export const MANAGER_LOGIN_REQUEST="MANAGER_LOGIN_REQUEST"
export const MANAGER_LOGIN_SUCCESS="MANAGER_LOGIN_SUCCESS"
export const MANAGER_LOGIN_FAIL="MANAGER_LOGIN_FAIL"


export const MANAGER_UPDATE_REQUEST="MANAGER_UPDATE_REQUEST"
export const MANAGER_UPDATE_SUCCESS="MANAGER_UPDATE_SUCCESS"
export const MANAGER_UPDATE_FAIL="MANAGER_UPDATE_FAIL"

export const MANAGER_DELETE_REQUEST="MANAGER_DELETE_REQUEST"
export const MANAGER_DELETE_SUCCESS="MANAGER_DELETE_SUCCESS"
export const MANAGER_DELETE_FAIL="MANAGER_DELETE_FAIL"

export const MANAGER_UPDATE_PASSWORD_REQUEST="MANAGER_UPDATE_PASSWORD_REQUEST"
export const MANAGER_UPDATE_PASSWORD_SUCCESS="MANAGER_UPDATE_PASSWORD_SUCCESS"
export const MANAGER_UPDATE_PASSWORD_FAIL="MANAGER_UPDATE_PASSWORD_FAIL"

export const GET_MANAGERS_REQUEST="GET_MANAGERS_REQUEST"
export const GET_MANAGERS_SUCCESS="GET_MANAGERS_SUCCESS"
export const GET_MANAGERS_FAIL="GET_MANAGERS_FAIL"


export const GET_MANAGER_REQUEST="GET_MANAGER_REQUEST"
export const GET_MANAGER_SUCCESS="GET_MANAGER_SUCCESS"
export const GET_MANAGER_FAIL="GET_MANAGER_FAIL"
